### ISSUE TITLE
Nice project but attribution would be great

### ISSUE THREAD

**Issue by dkundel** [rehooks/website#1]
This is a great project but it would be nice if you would attribute somewhere that a large part of this code is actually from the github.com/zeit/next-site 💖

**Comment by fouad** [comment]
@dkundel yep, in the middle of a few changes and one of them is a callout in readme for the awesome site the Next.js team put together — thanks for bumping!

**Comment by dkundel** [comment]
No problem :)

**Comment by fouad** [comment]
fixed in 97c0bfb9ff1cba9a07ff76ed3847a4d011cdfdf7!
